#!/bin/sh

set -e

if [ $# != 1 ]; then
    echo "Usage: $0 VERSION"
    exit 1
fi

VERSION=$1
NAME=$(basename $PWD)

git tag | grep -q ${VERSION} || (echo "Please tag ${VERSION} first!" && exit 1)

TARBALL="dist/${NAME}-${VERSION}.tar.gz"
if [ -r "$TARBALL" ]; then
  echo "$TARBALL exists!"
  exit 1
fi
git clone . tmp-sdist
cd tmp-sdist
git checkout -q ${VERSION}
cp -p ../man/${NAME}.1 man
cabal check
cabal configure
cabal sdist
mv $TARBALL ../dist/
cd ..
rm -rf tmp-sdist
