#!/bin/sh

# Todo
# - commands: update/refresh, diff
# - use tmpdirs for src trees?
# - rewrite in Haskell
# - copy in fedora spec files for subpkgs etc

# FIXME check branch
SPECS=${1:-$(ls ~/fedora/haskell/hackage/*/*.spec)}
CBLRPM=/usr/bin/cabal-rpm
#CBLRPM=cabal-rpm

mkdir -p pkgs
cd pkgs/

for p in $SPECS; do
    spec=$(basename $p)
    if [ -f "$spec" ]; then
        NV=$(rpmspec -q --qf "%{name}-%{version}" $spec | sed -e "s/^ghc-//")
        if [ -d "$NV" ]; then
            rm -rf $NV
        fi
    fi
    pkg=$(basename -s .spec $p)
    case $pkg in
        ghc-*) $CBLRPM spec -f $(echo $pkg | sed -e "s/^ghc-//") ;;
        *) $CBLRPM spec -f -b $pkg ;;
    esac
#    # filter out changelog
#    diff -u0 $p $spec | grep -v "generated by cabal-rpm" | grep -v "^@@ -"
done

echo "========================================"

git diff -U0 | grep -v "generated by cabal-rpm" | grep -v "^@@ -" | grep -v "^diff --git a/" | grep -v "^index "
