#!/bin/sh

# Todo
# - commands: update/refresh, diff
# - use tmpdirs for src trees?
# - rewrite in Haskell
# - copy in fedora spec files for subpkgs etc

set -e

#CBLRPM=/usr/bin/cabal-rpm
CBLRPM=cabal-rpm

mkdir -p pkgs
cd pkgs/
PKGS=${1:-$(ls)}

for p in $PKGS; do
    cd $p
    spec=$(ls *.spec)
    echo
    echo "# $p #"
    # if [ -f "$spec" ]; then
    #     NV=$(rpmspec -q --qf "%{name}-%{version}" $spec | sed -e "s/^ghc-//")
    #     if [ -d "$NV" ]; then
    #         rm -rf $NV
    #     fi
    # fi
    $CBLRPM spec
    diff -u0 $spec $spec.cblrpm | grep -v "generated by cabal-rpm" | grep -v "^@@ -" || :
    mv -f $spec.cblrpm $spec
    cd ..
done

echo "========================================"

! git diff -U0 . | grep -v "generated by cabal-rpm" | grep -v "^diff --git a/" | grep -v "^index "
