# generated by cabal-rpm-2.2.2 --subpackage
# https://docs.fedoraproject.org/en-US/packaging-guidelines/Haskell/

%global pkg_name aeson
%global pkgver %{pkg_name}-%{version}
%{?haskell_setup}

%global OneTuple OneTuple-0.4.2
%global generically generically-0.1.1
%global indexedtraversableinstances indexed-traversable-instances-0.1.2
%global semialign semialign-1.3.1
%global witherable witherable-0.4.2

%global subpkgs %{OneTuple} %{generically} %{indexedtraversableinstances} %{semialign} %{witherable}

# testsuite missing deps: tasty-golden

Name:           ghc-%{pkg_name}
Version:        2.1.2.1
# can only be reset when all subpkgs bumped
Release:        1%{?dist}
Summary:        Fast JSON parsing and encoding

License:        BSD-3-Clause
Url:            https://hackage.haskell.org/package/aeson
# Begin cabal-rpm sources:
Source0:        https://hackage.haskell.org/package/%{pkgver}/%{pkgver}.tar.gz
Source1:        https://hackage.haskell.org/package/%{OneTuple}/%{OneTuple}.tar.gz
Source2:        https://hackage.haskell.org/package/%{generically}/%{generically}.tar.gz
Source3:        https://hackage.haskell.org/package/%{indexedtraversableinstances}/%{indexedtraversableinstances}.tar.gz
Source4:        https://hackage.haskell.org/package/%{semialign}/%{semialign}.tar.gz
Source5:        https://hackage.haskell.org/package/%{witherable}/%{witherable}.tar.gz
Source6:        https://hackage.haskell.org/package/%{pkgver}/%{pkg_name}.cabal#/%{pkgver}.cabal
# End cabal-rpm sources

# Begin cabal-rpm deps:
BuildRequires:  ghc-Cabal-devel
BuildRequires:  ghc-rpm-macros-extra
#BuildRequires:  ghc-OneTuple-devel
BuildRequires:  ghc-QuickCheck-devel
BuildRequires:  ghc-attoparsec-devel
BuildRequires:  ghc-base-devel
BuildRequires:  ghc-base-compat-batteries-devel
BuildRequires:  ghc-bytestring-devel
BuildRequires:  ghc-containers-devel
BuildRequires:  ghc-data-fix-devel
BuildRequires:  ghc-deepseq-devel
BuildRequires:  ghc-dlist-devel
BuildRequires:  ghc-exceptions-devel
#BuildRequires:  ghc-generically-devel
BuildRequires:  ghc-hashable-devel
BuildRequires:  ghc-indexed-traversable-devel
BuildRequires:  ghc-primitive-devel
BuildRequires:  ghc-scientific-devel
#BuildRequires:  ghc-semialign-devel
BuildRequires:  ghc-strict-devel
BuildRequires:  ghc-tagged-devel
BuildRequires:  ghc-template-haskell-devel
BuildRequires:  ghc-text-devel
BuildRequires:  ghc-text-short-devel
BuildRequires:  ghc-th-abstraction-devel
BuildRequires:  ghc-these-devel
BuildRequires:  ghc-time-devel
BuildRequires:  ghc-time-compat-devel
BuildRequires:  ghc-unordered-containers-devel
BuildRequires:  ghc-uuid-types-devel
BuildRequires:  ghc-vector-devel
#BuildRequires:  ghc-witherable-devel
%if %{with ghc_prof}
#BuildRequires:  ghc-OneTuple-prof
BuildRequires:  ghc-QuickCheck-prof
BuildRequires:  ghc-attoparsec-prof
BuildRequires:  ghc-base-prof
BuildRequires:  ghc-base-compat-batteries-prof
BuildRequires:  ghc-bytestring-prof
BuildRequires:  ghc-containers-prof
BuildRequires:  ghc-data-fix-prof
BuildRequires:  ghc-deepseq-prof
BuildRequires:  ghc-dlist-prof
BuildRequires:  ghc-exceptions-prof
#BuildRequires:  ghc-generically-prof
BuildRequires:  ghc-hashable-prof
BuildRequires:  ghc-indexed-traversable-prof
BuildRequires:  ghc-primitive-prof
BuildRequires:  ghc-scientific-prof
#BuildRequires:  ghc-semialign-prof
BuildRequires:  ghc-strict-prof
BuildRequires:  ghc-tagged-prof
BuildRequires:  ghc-template-haskell-prof
BuildRequires:  ghc-text-prof
BuildRequires:  ghc-text-short-prof
BuildRequires:  ghc-th-abstraction-prof
BuildRequires:  ghc-these-prof
BuildRequires:  ghc-time-prof
BuildRequires:  ghc-time-compat-prof
BuildRequires:  ghc-unordered-containers-prof
BuildRequires:  ghc-uuid-types-prof
BuildRequires:  ghc-vector-prof
#BuildRequires:  ghc-witherable-prof
%endif
# for missing dep 'semialign':
BuildRequires:  ghc-semigroupoids-devel
BuildRequires:  ghc-transformers-devel
%if %{with ghc_prof}
BuildRequires:  ghc-semigroupoids-prof
BuildRequires:  ghc-transformers-prof
%endif
# for missing dep 'witherable':
BuildRequires:  ghc-base-orphans-devel
BuildRequires:  ghc-transformers-devel
%if %{with ghc_prof}
BuildRequires:  ghc-base-orphans-prof
BuildRequires:  ghc-transformers-prof
%endif
# End cabal-rpm deps

%description
A JSON parsing and encoding library optimized for ease of use and high
performance.

To get started, see the documentation for the 'Data.Aeson' module below.

(A note on naming: in Greek mythology, Aeson was the father of Jason.).


%package devel
Summary:        Haskell %{pkg_name} library development files
Provides:       %{name}-static = %{version}-%{release}
Provides:       %{name}-static%{?_isa} = %{version}-%{release}
%if %{defined ghc_version}
Requires:       ghc-compiler = %{ghc_version}
%endif
Requires:       %{name}%{?_isa} = %{version}-%{release}

%description devel
This package provides the Haskell %{pkg_name} library development files.


%if %{with haddock}
%package doc
Summary:        Haskell %{pkg_name} library documentation
BuildArch:      noarch
Requires:       ghc-filesystem

%description doc
This package provides the Haskell %{pkg_name} library documentation.
%endif


%if %{with ghc_prof}
%package prof
Summary:        Haskell %{pkg_name} profiling library
Requires:       %{name}-devel%{?_isa} = %{version}-%{release}
Supplements:    (%{name}-devel and ghc-prof)

%description prof
This package provides the Haskell %{pkg_name} profiling library.
%endif


%global main_version %{version}

%if %{defined ghclibdir}
%ghc_lib_subpackage -l BSD-3-Clause %{OneTuple}
%ghc_lib_subpackage -l BSD-3-Clause %{generically}
%ghc_lib_subpackage -l BSD-2-Clause %{indexedtraversableinstances}
%ghc_lib_subpackage -l BSD-3-Clause %{semialign}
%ghc_lib_subpackage -l BSD-3-Clause %{witherable}
%endif

%global version %{main_version}


%prep
# Begin cabal-rpm setup:
%setup -q -n %{pkgver} -a1 -a2 -a3 -a4 -a5
cp -bp %{SOURCE6} %{pkg_name}.cabal
# End cabal-rpm setup


%build
# Begin cabal-rpm build:
%ghc_libs_build %{subpkgs}
%ghc_lib_build
# End cabal-rpm build


%install
# Begin cabal-rpm install
%ghc_libs_install %{subpkgs}
%ghc_lib_install
# End cabal-rpm install


%files -f %{name}.files
# Begin cabal-rpm files:
%license LICENSE
# End cabal-rpm files


%files devel -f %{name}-devel.files
%doc README.markdown changelog.md


%if %{with haddock}
%files doc -f %{name}-doc.files
%license LICENSE
%endif


%if %{with ghc_prof}
%files prof -f %{name}-prof.files
%endif


%changelog
* Sun Feb 23 2025 Jens Petersen <juhpetersen@gmail.com> - 2.1.2.1-1
- spec file generated by cabal-rpm-2.2.2
